// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrpUW27qo_oyBggMOojQ4bwIjsd6PDlE4',
    appId: '1:986248620529:web:ef79d41edb9e7d4a927c50',
    messagingSenderId: '986248620529',
    projectId: 'habit-hive-6b7bc',
    authDomain: 'habit-hive-6b7bc.firebaseapp.com',
    storageBucket: 'habit-hive-6b7bc.firebasestorage.app',
    measurementId: 'G-4B5F132VFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMt2JQ9TG--vvseeVpc1mMx0QxFrvWNI',
    appId: '1:986248620529:android:8c3706b96bad15b2927c50',
    messagingSenderId: '986248620529',
    projectId: 'habit-hive-6b7bc',
    storageBucket: 'habit-hive-6b7bc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrpUW27qo_oyBggMOojQ4bwIjsd6PDlE4',
    appId: '1:986248620529:web:a56e833014e6430a927c50',
    messagingSenderId: '986248620529',
    projectId: 'habit-hive-6b7bc',
    authDomain: 'habit-hive-6b7bc.firebaseapp.com',
    storageBucket: 'habit-hive-6b7bc.firebasestorage.app',
    measurementId: 'G-7HDPV8L9T3',
  );
}
